### ISSUE TITLE
Attempt to install using docker-scaffold instructions not working:

### ISSUE THREAD

**Issue by lawrenceong001** [drupalwxt/docker-scaffold#8]
hello,

I'm trying to install this using Windows 10 WSL2 Ubuntu 20 image. 

when I tried `export COMPOSER_MEMORY_LIMIT=-1 && composer install`, I get the following error:

```
Composer could not find a composer.json file in /home/lawrence/docker
To initialize a project, please create a composer.json file. See https://getcomposer.org/basic-usage
PHP Fatal error:  Uncaught Error: Call to undefined method Composer\Console\Application::areExceptionsCaught() in phar:///mnt/c/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:422
Stack trace:
#0 phar:///mnt/c/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Command/BaseCommand.php(63): Composer\Console\Application->getComposer()
#1 phar:///mnt/c/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Command/InstallCommand.php(96): Composer\Command\BaseCommand->getComposer()
#2 phar:///mnt/c/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Command/Command.php(245): Composer\Command\InstallCommand->execute()
#3 phar:///mnt/c/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run()
#4 phar:///mnt/c/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand()
#5 phar:///mnt/c/ProgramData/ComposerSetup/bin/comp in phar:///mnt/c/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php on line 422

Fatal error: Uncaught Error: Call to undefined method Composer\Console\Application::areExceptionsCaught() in phar:///mnt/c/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:422
Stack trace:
#0 phar:///mnt/c/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Command/BaseCommand.php(63): Composer\Console\Application->getComposer()
#1 phar:///mnt/c/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Command/InstallCommand.php(96): Composer\Command\BaseCommand->getComposer()
#2 phar:///mnt/c/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Command/Command.php(245): Composer\Command\InstallCommand->execute()
#3 phar:///mnt/c/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run()
#4 phar:///mnt/c/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand()
#5 phar:///mnt/c/ProgramData/ComposerSetup/bin/comp in phar:///mnt/c/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php on line 422
```

any advice on how to resolve this? tks.

**Comment by sylus** [comment]
Unfortunately this would be more a composer oriented question so might be best to ask there.
